name: my_app
description: "Admin Chat App for managing user support in mobile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  http: ^1.2.1
  flutter_local_notifications: ^17.1.0
  provider: ^6.1.2
  file_picker: ^10.1.2
  url_launcher: ^6.2.5
  # Optional but helpful
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  
  # Optional: add custom fonts here if needed
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
